# server port ?? ??? ??
server:
  port: 8080


# driver config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers
  mail:
    host: smtp.gmail.com
    port: 587
    username: myclassplanner01@gmail.com
    password: grnywssuwrsngmeq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# mybatis ????
mybatis:
  mapper-locations: mappers/*.xml
